services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app/database.db
    environment:
      - DB_PATH=/app/database.db

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
