version: '3.8'

services:
  backend:
    build: ./server
    container_name: pms-backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - database_volume:/app/database.db
    environment:
      - GIN_MODE=release
      - DB_PATH=/app/database.db
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pms-network

  frontend:
    build: ./client
    container_name: pms-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
      - VITE_SWAGGER_URL=http://localhost:8080/swagger/doc.json
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - pms-network

volumes:
  database_volume:


networks:
  pms-network:
    driver: bridge
